
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
rules:
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - watch
  - create
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
